# CountVectorizer

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

df = pd.read_csv('../all_games.csv', encoding='utf-8')
df.head()

name        platform        release_date  \
0  The Legend of Zelda: Ocarina of Time     Nintendo 64   November 23, 1998   
1              Tony Hawk's Pro Skater 2     PlayStation  September 20, 2000   
2                   Grand Theft Auto IV   PlayStation 3      April 29, 2008   
3                           SoulCalibur       Dreamcast   September 8, 1999   
4                   Grand Theft Auto IV        Xbox 360      April 29, 2008   

                                             summary  meta_score user_review  
0  As a young boy, Link is tricked by Ganondorf, ...          99         9.1  
1  As most major publishers' development efforts ...          98         7.4  
2  [Metacritic's 2008 PS3 Game of the Year; Also ...          98         7.7  
3  This is a tale of souls and swords, transcendi...          98         8.4  
4  [Metacritic's 2008 Xbox 360 Game of the Year; ...          98         7.9

In [3]:
summary = df['summary'][0]
#summary = list(summary)
#3summary
#summary
summary = ['As a young boy, Link is tricked by Ganondorf, the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm, where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create, so with the help of Rauru he travels through time gathering the powers of the Seven Sages.']

In [4]:
#summary = df['summary'].values.astype('U')
#df['summary'].values.tolist()

#df['sy'].apply(lambda x: np.str_(x))
summary = df['summary'].apply(lambda x: np.str_(x))
summary

0        As a young boy, Link is tricked by Ganondorf, ...
1        As most major publishers' development efforts ...
2        [Metacritic's 2008 PS3 Game of the Year; Also ...
3        This is a tale of souls and swords, transcendi...
4        [Metacritic's 2008 Xbox 360 Game of the Year; ...
                               ...                        
18795    Fast & Furious: Showdown takes some of the fra...
18796    Drake is out for revenge in a supernatural Hon...
18797    Head out on a journey of redemption, driven by...
18798    (Formerly known as "The War Z") It has been 5 ...
18799    The Leisure Suit Larry: Box Office Bust video ...
Name: summary, Length: 18800, dtype: object

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
count_matrix = count_vect.fit_transform(summary)
count_array = count_matrix.toarray()

summaryData = pd.DataFrame(data=count_array, columns=count_vect.get_feature_names())
summaryData.head()

00  000  000km  000s  001  007  0079  0083  00s  01  ...  œalan  œdead  \
0   0    0      0     0    0    0     0     0    0   0  ...      0      0   
1   0    0      0     0    0    0     0     0    0   0  ...      0      0   
2   0    0      0     0    0    0     0     0    0   0  ...      0      0   
3   0    0      0     0    0    0     0     0    0   0  ...      0      0   
4   0    0      0     0    0    0     0     0    0   0  ...      0      0   

   œfallen  œthe  œuntold  λcore  сity  ナックル  ベア  finding  
0        0     0        0      0     0     0   0       0  
1        0     0        0      0     0     0   0       0  
2        0     0        0      0     0     0   0       0  
3        0     0        0      0     0     0   0       0  
4        0     0        0      0     0     0   0       0  

[5 rows x 38923 columns]

In [10]:
summaryData.columns

Index(['00', '000', '000km', '000s', '001', '007', '0079', '0083', '00s', '01',
       ...
       'œalan', 'œdead', 'œfallen', 'œthe', 'œuntold', 'λcore', 'сity', 'ナックル',
       'ベア', 'finding'],
      dtype='object', length=38923)

In [13]:
vectorizer = CountVectorizer()

vectorizer.fit(summary)
print("Vocabulary: ", vectorizer.vocabulary_)

vector = vectorizer.transform(summary)

print("Encoded Document is:")
print(vector.toarray())

Vocabulary:  {'as': 2631, 'young': 38608, 'boy': 4834, 'link': 19947, 'is': 17895, 'tricked': 35475, 'by': 5428, 'ganondorf': 13966, 'the': 34456, 'king': 18878, 'of': 23907, 'gerudo': 14226, 'thieves': 34536, 'evil': 11811, 'human': 16500, 'uses': 36541, 'to': 34868, 'gain': 13822, 'access': 945, 'sacred': 29445, 'realm': 27637, 'where': 37764, 'he': 15639, 'places': 25702, 'his': 16087, 'tainted': 33844, 'hands': 15374, 'on': 24037, 'triforce': 35495, 'and': 1970, 'transforms': 35310, 'beautiful': 3787, 'hyrulean': 16669, 'landscape': 19378, 'into': 17699, 'barren': 3528, 'wasteland': 37512, 'determined': 9414, 'fix': 12879, 'problems': 26522, 'helped': 15843, 'create': 8056, 'so': 31661, 'with': 38049, 'help': 15842, 'rauru': 27526, 'travels': 35387, 'through': 34644, 'time': 34775, 'gathering': 14038, 'powers': 26226, 'seven': 30422, 'sages': 29479, 'most': 22434, 'major': 20661, 'publishers': 26856, 'development': 9450, 'efforts': 10866, 'shift': 30660, 'any': 2162, 'number': 2369

Encoded Document is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
