# CountVectorizer

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

df = pd.read_csv('../all_games.csv', encoding='utf-8')
df.head()

name        platform        release_date  \
0  The Legend of Zelda: Ocarina of Time     Nintendo 64   November 23, 1998   
1              Tony Hawk's Pro Skater 2     PlayStation  September 20, 2000   
2                   Grand Theft Auto IV   PlayStation 3      April 29, 2008   
3                           SoulCalibur       Dreamcast   September 8, 1999   
4                   Grand Theft Auto IV        Xbox 360      April 29, 2008   

                                             summary  meta_score user_review  
0  As a young boy, Link is tricked by Ganondorf, ...          99         9.1  
1  As most major publishers' development efforts ...          98         7.4  
2  [Metacritic's 2008 PS3 Game of the Year; Also ...          98         7.7  
3  This is a tale of souls and swords, transcendi...          98         8.4  
4  [Metacritic's 2008 Xbox 360 Game of the Year; ...          98         7.9

In [2]:
#summary = df['summary'].values.astype('U')
#df['summary'].values.tolist()

#df['sy'].apply(lambda x: np.str_(x))
summary = df['summary'].apply(lambda x: np.str_(x))
summary

0        As a young boy, Link is tricked by Ganondorf, ...
1        As most major publishers' development efforts ...
2        [Metacritic's 2008 PS3 Game of the Year; Also ...
3        This is a tale of souls and swords, transcendi...
4        [Metacritic's 2008 Xbox 360 Game of the Year; ...
                               ...                        
18795    Fast & Furious: Showdown takes some of the fra...
18796    Drake is out for revenge in a supernatural Hon...
18797    Head out on a journey of redemption, driven by...
18798    (Formerly known as "The War Z") It has been 5 ...
18799    The Leisure Suit Larry: Box Office Bust video ...
Name: summary, Length: 18800, dtype: object

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
count_matrix = count_vect.fit_transform(summary)
count_array = count_matrix.toarray()

summaryData = pd.DataFrame(data=count_array, columns=count_vect.get_feature_names())
summaryData.head()

00  000  000km  000s  001  007  0079  0083  00s  01  ...  œalan  œdead  \
0   0    0      0     0    0    0     0     0    0   0  ...      0      0   
1   0    0      0     0    0    0     0     0    0   0  ...      0      0   
2   0    0      0     0    0    0     0     0    0   0  ...      0      0   
3   0    0      0     0    0    0     0     0    0   0  ...      0      0   
4   0    0      0     0    0    0     0     0    0   0  ...      0      0   

   œfallen  œthe  œuntold  λcore  сity  ナックル  ベア  finding  
0        0     0        0      0     0     0   0       0  
1        0     0        0      0     0     0   0       0  
2        0     0        0      0     0     0   0       0  
3        0     0        0      0     0     0   0       0  
4        0     0        0      0     0     0   0       0  

[5 rows x 38923 columns]

In [4]:
summaryData.columns

Index(['00', '000', '000km', '000s', '001', '007', '0079', '0083', '00s', '01',
       ...
       'œalan', 'œdead', 'œfallen', 'œthe', 'œuntold', 'λcore', 'сity', 'ナックル',
       'ベア', 'finding'],
      dtype='object', length=38923)

In [5]:
vectorizer = CountVectorizer()

vectorizer.fit(summary)
print("Vocabulary: ", vectorizer.vocabulary_)

vector = vectorizer.transform(summary)

print("Encoded Document is:")
print(vector.toarray())

Vocabulary:  {'as': 2631, 'young': 38608, 'boy': 4834, 'link': 19947, 'is': 17895, 'tricked': 35475, 'by': 5428, 'ganondorf': 13966, 'the': 34456, 'king': 18878, 'of': 23907, 'gerudo': 14226, 'thieves': 34536, 'evil': 11811, 'human': 16500, 'uses': 36541, 'to': 34868, 'gain': 13822, 'access': 945, 'sacred': 29445, 'realm': 27637, 'where': 37764, 'he': 15639, 'places': 25702, 'his': 16087, 'tainted': 33844, 'hands': 15374, 'on': 24037, 'triforce': 35495, 'and': 1970, 'transforms': 35310, 'beautiful': 3787, 'hyrulean': 16669, 'landscape': 19378, 'into': 17699, 'barren': 3528, 'wasteland': 37512, 'determined': 9414, 'fix': 12879, 'problems': 26522, 'helped': 15843, 'create': 8056, 'so': 31661, 'with': 38049, 'help': 15842, 'rauru': 27526, 'travels': 35387, 'through': 34644, 'time': 34775, 'gathering': 14038, 'powers': 26226, 'seven': 30422, 'sages': 29479, 'most': 22434, 'major': 20661, 'publishers': 26856, 'development': 9450, 'efforts': 10866, 'shift': 30660, 'any': 2162, 'number': 2369

Encoded Document is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
vector.shape

(18800, 38923)

In [7]:
games_pc = df.loc[lambda df: df['platform'] == ' PC']
games_pc

name platform       release_date  \
10                  Disco Elysium: The Final Cut       PC     March 30, 2021   
24                                   Half-Life 2       PC  November 16, 2004   
25                            Grand Theft Auto V       PC     April 13, 2015   
32                                The Orange Box       PC   October 10, 2007   
38                                     Half-Life       PC  November 19, 1998   
...                                          ...      ...                ...   
18784               Terrawars: New York Invasion       PC       July 6, 2006   
18786                                 Postal III       PC  December 21, 2011   
18791             FlatOut 3: Chaos & Destruction       PC  December 13, 2011   
18798  Infestation: Survivor Stories (The War Z)       PC   October 15, 2012   
18799        Leisure Suit Larry: Box Office Bust       PC     March 31, 2009   

                                                 summary  meta_score  \
10     Disco Elysium - The Final Cut is the definitiv...          97   
24     [Metacritic's 2004 PC Game of the Year] By tak...          96   
25     Los Santos: a sprawling sun-soaked metropolis ...          96   
32     Games included in The Orange Box compilation: ...          96   
38     Half-Life combines great storytelling in the t...          96   
...                                                  ...         ...   
18784  Without warning, the world is overrun by an al...          24   
18786  The Postal series continues in this third inst...          24   
18791  FlatOut 3: Chaos & Destruction brings a new di...          23   
18798  (Formerly known as "The War Z") It has been 5 ...          20   
18799  The Leisure Suit Larry: Box Office Bust video ...          20   

      user_review  
10            8.3  
24            9.2  
25            7.8  
32            9.3  
38            9.1  
...           ...  
18784         2.2  
18786         3.1  
18791         3.0  
18798         1.7  
18799         2.0  

[4864 rows x 6 columns]

In [11]:
summary_pc = games_pc['summary'].apply(lambda x: np.str_(x))
list(summary_pc)

["Disco Elysium - The Final Cut is the definitive edition of the smash-hit RPG. Pursue your political dreams in new quests, meet and question more of the city's locals, and explore a whole extra area. Full voice-acting, controller support, and expanded language options also included. Get even more out of this award-winning open world. You're a detective with a unique skill system at your disposal and a whole city block to carve your path across. Interrogate unforgettable characters, crack murders, or take bribes. Become a hero or an absolute disaster of a human being.",
 "[Metacritic's 2004 PC Game of the Year] By taking the suspense, challenge and visceral charge of the original, and adding startling new realism and responsiveness, Half-Life 2 opens the door to a world where the player's presence affects everything around him, from the physical environment to the behaviors -- even the emotions -- of both friends and enemies. The player again picks up the crowbar of research scientist 

In [18]:
vectorizer = CountVectorizer()

vectorizer.fit(summary_pc)
print("Vocabulary: ", vectorizer.vocabulary_)

vector = vectorizer.transform(summary_pc)

print("Encoded Document is:")
print(vector.toarray())

Vocabulary:  {'disco': 6104, 'elysium': 6909, 'the': 20838, 'final': 8047, 'cut': 5260, 'is': 11096, 'definitive': 5635, 'edition': 6759, 'of': 14450, 'smash': 19067, 'hit': 9991, 'rpg': 17754, 'pursue': 16366, 'your': 23341, 'political': 15743, 'dreams': 6474, 'in': 10540, 'new': 14096, 'quests': 16461, 'meet': 12991, 'and': 1203, 'question': 16455, 'more': 13565, 'city': 4021, 'locals': 12235, 'explore': 7595, 'whole': 22888, 'extra': 7643, 'area': 1475, 'full': 8608, 'voice': 22478, 'acting': 644, 'controller': 4722, 'support': 20229, 'expanded': 7538, 'language': 11828, 'options': 14619, 'also': 1048, 'included': 10573, 'get': 8925, 'even': 7395, 'out': 14749, 'this': 20902, 'award': 1952, 'winning': 22989, 'open': 14563, 'world': 23116, 'you': 23333, 're': 16706, 'detective': 5895, 'with': 23031, 'unique': 21887, 'skill': 18908, 'system': 20431, 'at': 1744, 'disposal': 6175, 'block': 2724, 'to': 21096, 'carve': 3584, 'path': 15120, 'across': 641, 'interrogate': 10940, 'unforgettab

Encoded Document is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
vector.shape

(4864, 23475)

In [20]:
cat_in_the_hat_docs=[
       "One Cent, Two Cents, Old Cent, New Cent: All About Money (Cat in the Hat's Learning Library",
       "Inside Your Outside: All About the Human Body (Cat in the Hat's Learning Library)",
       "Oh, The Things You Can Do That Are Good for You: All About Staying Healthy (Cat in the Hat's Learning Library)",
       "On Beyond Bugs: All About Insects (Cat in the Hat's Learning Library)",
       "There's No Place Like Space: All About Our Solar System (Cat in the Hat's Learning Library)" 
      ]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(cat_in_the_hat_docs)
count_vector=cv.fit_transform(cat_in_the_hat_docs)


cv = CountVectorizer(cat_in_the_hat_docs,stop_words=["all","in","the","is","and"])
count_vector=cv.fit_transform(cat_in_the_hat_docs)
count_vector.shape


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass input=["One Cent, Two Cents, Old Cent, New Cent: All About Money (Cat in the Hat's Learning Library", "Inside Your Outside: All About the Human Body (Cat in the Hat's Learning Library)", "Oh, The Things You Can Do That Are Good for You: All About Staying Healthy (Cat in the Hat's Learning Library)", "On Beyond Bugs: All About Insects (Cat in the Hat's Learning Library)", "There's No Place Like Space: All About Our Solar System (Cat in the Hat's Learning Library)"] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


(5, 40)